---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - namespace.extension
  resources:
  - namespaceclasssynchronizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - namespace.extension.test.akuity
  resources:
  - namespaceclasses
  - namespaceclasssynchronizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - namespace.extension.test.akuity
  resources:
  - namespaceclasses/finalizers
  - namespaceclasssynchronizers/finalizers
  verbs:
  - update
- apiGroups:
  - namespace.extension.test.akuity
  resources:
  - namespaceclasses/status
  - namespaceclasssynchronizers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
