## Append samples of your project ##
resources:
- namespace.extension_v1_namespaceclass.yaml
- namespace.extension_v1_namespaceclasssynchronizer.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
