apiVersion: namespace.extension.test.akuity/v1
kind: NamespaceClass
metadata:
  name: isolated-profile
  namespace: akuity-system
spec:
  clusterRoles:
    - name: namespace-viewer
      rules:
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list"]
  NetworkPolicies:
    - name: allow-http-https
      spec:
        podSelector:
          matchLabels:
            tier: frontend_changed