apiVersion: namespace.extension.test.akuity/v1
kind: NamespaceClass
metadata:
  name: isolated-profile
  namespace: akuity-system
spec:
  NetworkPolicies:
    - name: allow-http-https
      spec:
        podSelector:
          matchLabels:
            tier: frontend
  configMaps:
    - name: frontend-config
      data:
        API_URL: "https://example.com"