apiVersion: namespace.extension.test.akuity/v1
kind: NamespaceClassSynchronizer
metadata:
  labels:
    app.kubernetes.io/name: akuity
    app.kubernetes.io/managed-by: kustomize
  name: namespace-that-is-managing-sample
  namespace: akuity-system
spec:
Spec:
  require_update:          true
  target_namespace_class:  isolated-profile

-- DO NOT APPLY THIS ONE. THIS WILL BE AUTO MANAGED BY THE CONTROLLER.